alura/urls.py
from django.urls import path
from . import views

app_name = 'alura'

urlpatterns =[
    path('cursos',views.index,name='index'),
    path('curso/<int:curso_id>',views.curso,name='curso'),
    path('carrito',views.carrito,name='carrito'),
    path('carrito/add/<int:curso_id>',views.agregar_carrito,name='agregarcarrito'),
    path('carrito/del/<int:curso_id>',views.eliminar_carrito,name='eliminarcarrito'),
    path('carrito/clear',views.limpiar_carrito,name='limpiarcarrito'),
    path('usuario/add',views.crear_usuario,name='crearusuario'),
    path('cuenta',views.cuenta_usuario,name='cuentausuario'),
    path('login',views.login_usuario,name='loginusuario'),
    path('salir',views.logout_usuario,name='logoutusuario'),
    path('cliente/update',views.actualizar_cliente,name='actualizarcliente'),
    path('pedido',views.pedido,name='pedido'),
    path('pedido/add',views.registrar_pedido,name='registrar_pedido'),
    path('paypaltest',views.view_that_asks_for_money,name='paypaltest'),
    path('gracias',views.gracias,name='gracias'),
    path('',views.paginaalura,name='home'),
]

proyectofinal/urls.py
from django.contrib import admin
from django.urls import path,include
from alura import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('paypal/', include("paypal.standard.ipn.urls")),
    path('',include('alura.urls')),
    #path('', views.helloworlds)
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

alura/models.py
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.
class Categoria(models.Model):
    nombre = models.CharField(max_length=200)
    fecha_registro = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'tbl_categoria'

    def __str__(self):
        return self.nombre

class Area(models.Model):
    nombre = models.CharField(max_length=200)
    fecha_registro = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'tbl_area'

    def __str__(self):
        return self.nombre

class Curso(models.Model):
    categoria = models.ForeignKey(Categoria,on_delete=models.RESTRICT)
    area = models.ForeignKey(Area,on_delete=models.RESTRICT)
    curso = models.CharField(max_length=255,null=True)
    descripcion = models.TextField(null=True)
    precio = models.DecimalField(max_digits=6,decimal_places=2)
    fecha_inicio = models.DateField(null=False)
    popularidad =models.DecimalField(max_digits=4,decimal_places=2)
    profesor = models.CharField(max_length=150,null=True)
    fecha_lanzamiento = models.DateField(null=False)
    idioma = models.CharField(max_length=25,null=True)
    subtitulo = models.CharField(max_length=25,null=True)
    dificultad = models.CharField(max_length=50,null=True)
    duracion = models.CharField(max_length=4,null=True)
    estudiantes = models.CharField(max_length=6,null=True)
    nota_a =models.CharField(max_length=200,null=True)
    nota_b =models.CharField(max_length=200,null=True)
    nota_c =models.CharField(max_length=200,null=True)
    sku = models.CharField(max_length=10,null=True,unique=True)

    class Meta:
        db_table = 'tbl_curso'

    def __str__(self):
        return self.curso

@receiver(post_save,sender=Curso)
def generar_sku(sender,instance,created,**kwargs):
    if created:
        categoria_cod = instance.categoria.nombre[:2].upper()
        correlativo = str(Curso.objects.count()).zfill(3)
        instance.sku = f'{categoria_cod}{correlativo}'
        instance.save()

class CursoImagen(models.Model):
    curso = models.ForeignKey(Curso,on_delete=models.RESTRICT)
    imagen = models.ImageField(upload_to='galeria',blank=True)
    orden = models.IntegerField(default=1)
    fecha_registro = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'tbl_curso_imagen'
        verbose_name_plural = 'Imagenes del Curso'

    def __str__(self):
        return str(self.imagen)
##modelos para usuarion###
from django.contrib.auth.models import User

class Cliente(models.Model):
    usuario = models.OneToOneField(User,on_delete=models.RESTRICT)
    nombre = models.CharField(max_length=255)
    dni= models.CharField(max_length=8)
    sexo = models.CharField(max_length=1)
    telefono = models.CharField(max_length=20)
    fecha_nacimiento = models.DateField(null=True)
    direccion = models.TextField()

    class Meta:
        db_table = 'tbl_cliente'

    def __str__(self):
        return self.nombre

##modelos pedido

class Pedido(models.Model):

    ESTADO_CHOICES=(
        ('0','Solicitado'),
        ('1','Pagado')
    )

    cliente = models.ForeignKey(Cliente,on_delete=models.RESTRICT)
    fecha_registro = models.DateTimeField(auto_now=True)
    nro_pedido = models.CharField(max_length=20,null=True)
    monto_total = models.DecimalField(max_digits=10,decimal_places=2,default=0)
    estado = models.CharField(max_length=1,default='0',choices=ESTADO_CHOICES)

    class Meta:
        db_table = 'tbl_pedido'

    def __str__(self):
        return self.nro_pedido

class PedidoDetalle(models.Model):
    pedido = models.ForeignKey(Pedido,on_delete=models.RESTRICT)
    producto = models.ForeignKey(Curso,on_delete=models.RESTRICT)
    cantidad = models.IntegerField(default=1)
    subtotal = models.DecimalField(max_digits=10,decimal_places=2)

    class Meta:
        db_table = 'tbl_pedido_detalle'

    def __str__(self):
        return self.producto.curso

alura/forms.py
from django import forms

class DateInput(forms.DateInput):
    input_type='date'

class ClienteForm(forms.Form):
    SEXO_CHOICES=(
        ('M','Masculino'),
        ('F','Femenino')
    )
    dni = forms.CharField(label='DNI',max_length=8)
    nombre = forms.CharField(label='Nombres',max_length=200,required=True)
    apellidos = forms.CharField(label='Apellidos',max_length=200,required=True)
    email = forms.EmailField(label='Email',required=True)
    direccion = forms.CharField(label='Dirección',widget=forms.Textarea)
    telefono = forms.CharField(label='Telefono',max_length=20)
    sexo = forms.ChoiceField(label='Sexo',choices=SEXO_CHOICES,widget=forms.Select(attrs={'class':'form-select'}))
    fecha_nacimiento = forms.DateField(label='Fecha Nac',input_formats=['%Y-%m-%d'],widget=DateInput)

alura/views.py
from django.shortcuts import render,redirect
from .models import (
    Categoria,Area,Curso,CursoImagen
)
#from django.http import HttpResponse

# Create your views here.
def paginaalura(request):
    return render(request,'home.html')

def index(request):
    lista_categorias = Categoria.objects.all()
    lista_areas = Area.objects.all()

    categoria_id = request.GET.get('cat')
    area_id = request.GET.get('are')
    if categoria_id:
        categoria_seleccionada = Categoria.objects.get(pk=categoria_id)
        lista_cursos = Curso.objects.filter(categoria=categoria_seleccionada)
    elif area_id:
        area_seleccionada = Area.objects.get(pk=area_id)
        lista_cursos = Curso.objects.filter(area=area_seleccionada)
    else:
        lista_cursos = Curso.objects.all()

    context = {
        'categorias':lista_categorias,
        'areas': lista_areas,
        'cursos': lista_cursos
    }
    
    return render(request, 'index.html',context)

def curso(request,curso_id):
    obj_curso = Curso.objects.get(pk=curso_id)
    context = {
        'curso':obj_curso
    }
    return render(request,'curso.html',context)

###carrito
from .cart import Cart

def carrito(request):
    return render(request, 'carrito.html')

def agregar_carrito(request,curso_id):
    if request.method == 'POST':
        cantidad = int(request.POST['cantidad'])
    else:
        cantidad = 1
    obj_curso = Curso.objects.get(pk=curso_id)
    curso_imagenes = CursoImagen.objects.filter(curso=obj_curso)
    print(curso_imagenes[0])

    carrito = Cart(request)
    carrito.add(obj_curso,cantidad,curso_imagenes[0].imagen.url)

    if request.method == 'GET':
        return redirect('/cursos')

    return render(request,'carrito.html')

def eliminar_carrito(request,curso_id):
    obj_curso = Curso.objects.get(pk=curso_id)
    carrito = Cart(request)
    carrito.delete(obj_curso)

    if request.GET.get('hd') =='1':
        return redirect('/cursos')

    return render(request,'carrito.html')

def limpiar_carrito(request):
    carrito = Cart(request)
    carrito.clear()

    return render(request, 'carrito.html')

###usuario y login ###
from django.contrib.auth.models import User

from django.contrib.auth import login,logout,authenticate
from django.contrib.auth.decorators import login_required


def crear_usuario(request):
    if request.method== 'POST':
        data_usuario = request.POST['nuevo_usuario']
        data_password = request.POST['nuevo_password']

        obj_usuario = User.objects.create_user(username=data_usuario,password=data_password)

        if obj_usuario is not None:
            login(request,obj_usuario)
            return redirect('/cuenta')

    return render(request, 'login.html')

def login_usuario(request):
    
    pagina_destino = request.GET.get('next',None)
    context = {
        'destino':pagina_destino
    }
    if request.method== 'POST':
        data_usuario = request.POST['login_usuario']
        data_password= request.POST['login_password']
        data_destino = request.POST['destino']

        obj_usuario= authenticate(request,username=data_usuario,password=data_password)

        if obj_usuario is not None:
            login(request,obj_usuario)

            if data_destino != 'None':
                return redirect(data_destino)

            return redirect('/cuenta')
        else:
            context = {
                'mensajeError': 'Datos Incorrectos'
            }

    return render(request, 'login.html',context)

def logout_usuario(request):
    logout(request)
    return redirect('/')

####cliente####

from .models import Cliente
from .forms import ClienteForm

@login_required(login_url='/login')
def cuenta_usuario(request):
    data = {}

    if request.user.first_name != '':
        data.update({'nombre':request.user.first_name})

    if request.user.last_name != '':
        data.update({'apellidos':request.user.last_name})

    data.update({'email':request.user.username})

    ### cargamos datos cliente

    try:
        obj_cliente = Cliente.objects.get(usuario=request.user)
        data_cliente = {
            'direccion': obj_cliente.direccion,
            'telefono':obj_cliente.telefono,
            'dni':obj_cliente.dni,
            'fecha_nacimiento':obj_cliente.fecha_nacimiento,
            'sexo': obj_cliente.sexo
        }
    except:
        data_cliente = {
            'direccion': '',
            'telefono':'',
            'dni':'',
            'fecha_nacimiento':'',
            'sexo':'M'
        }

    data.update(data_cliente)


    form_cliente = ClienteForm(data)
    context={
        'frm_cliente':form_cliente
    }
    return render(request,'cuenta.html',context)

@login_required(login_url='/login')
def actualizar_cliente(request):
    if request.method== 'POST':
        frm_cliente = ClienteForm(request.POST)
        if frm_cliente.is_valid():
            data = frm_cliente.cleaned_data

            #update user
            obj_usuario = User.objects.get(pk=request.user.id)
            obj_usuario.first_name = data['nombre']
            obj_usuario.last_name = data['apellidos']
            obj_usuario.email=data['email']
            obj_usuario.save()

            try:
                obj_cliente = Cliente.objects.get(usuario=obj_usuario)
            except:
                obj_cliente = Cliente()
                obj_cliente.usuario = obj_usuario

            obj_cliente.dni = data['dni']
            obj_cliente.direccion = data['direccion']
            obj_cliente.telefono = data['telefono']
            obj_cliente.fecha_nacimiento = data['fecha_nacimiento']
            obj_cliente.sexo=data['sexo']
            obj_cliente.save()
            mensaje = 'Datos Guardados'

    return redirect('/cuenta')

###pedido###

from .models import Pedido,PedidoDetalle

@login_required(login_url='/login')
def pedido(request):
    data = {}

    if request.user.first_name != '':
        data.update({'nombre':request.user.first_name})

    if request.user.last_name != '':
        data.update({'apellidos':request.user.last_name})

    data.update({'email':request.user.username})

    ### cargamos datos cliente

    try:
        obj_cliente = Cliente.objects.get(usuario=request.user)
        data_cliente = {
            'direccion': obj_cliente.direccion,
            'telefono':obj_cliente.telefono,
            'dni':obj_cliente.dni,
            'fecha_nacimiento':obj_cliente.fecha_nacimiento,
            'sexo': obj_cliente.sexo
        }
    except:
        data_cliente = {
            'direccion': '',
            'telefono':'',
            'dni':'',
            'fecha_nacimiento':'',
            'sexo':'M'
        }

    data.update(data_cliente)


    form_cliente = ClienteForm(data)
    context={
        'frm_cliente':form_cliente
    }
    return render(request,'pedido.html',context)

from django.urls import reverse
from paypal.standard.forms import PayPalPaymentsForm

@login_required(login_url='/login')
def registrar_pedido(request):
    if request.method == 'POST':
        frm_cliente = ClienteForm(request.POST)
        if frm_cliente.is_valid():
            data = frm_cliente.cleaned_data

            #update user
            obj_usuario = User.objects.get(pk=request.user.id)
            obj_usuario.first_name = data['nombre']
            obj_usuario.last_name = data['apellidos']
            obj_usuario.email=data['email']
            obj_usuario.save()

            try:
                obj_cliente = Cliente.objects.get(usuario=obj_usuario)
            except:
                obj_cliente = Cliente()
                obj_cliente.usuario = obj_usuario

            obj_cliente.dni = data['dni']
            obj_cliente.direccion = data['direccion']
            obj_cliente.telefono = data['telefono']
            obj_cliente.fecha_nacimiento = data['fecha_nacimiento']
            obj_cliente.sexo=data['sexo']
            obj_cliente.save()

        #registrar pedido
        
        monto_total= float(request.session.get('cart_total'))
        obj_pedido = Pedido()
        obj_pedido.cliente = obj_cliente
        obj_pedido.save()
        nro_pedido = 'PEP' + obj_pedido.fecha_registro.strftime('%Y')+ str(obj_pedido.id)
        obj_pedido.nro_pedido = nro_pedido
        obj_pedido.save()

        carrito = request.session.get('cart')
        for key,value in carrito.items():
            obj_producto = Curso.objects.get(pk=value['curso_id'])
            obj_pedido_detalle = PedidoDetalle()
            obj_pedido_detalle.pedido = obj_pedido
            obj_pedido_detalle.producto = obj_producto
            obj_pedido_detalle.cantidad = int(value['cantidad'])
            obj_pedido_detalle.subtotal = float(value['subtotal'])
            obj_pedido_detalle.save()

        ## btn paypal
        paypal_dict = {
        "business": "sb-qyxr130010752@business.example.com",
        "amount": monto_total,
        "item_name": "PEDIDO NRO: " + obj_pedido.nro_pedido,
        "invoice": obj_pedido.id,
        "notify_url": request.build_absolute_uri(reverse('paypal-ipn')),
        "return": request.build_absolute_uri(reverse('alura:gracias')),
        "cancel_return": request.build_absolute_uri(reverse('alura:index')),
        }

        # Create the instance.
        frm_paypal = PayPalPaymentsForm(initial=paypal_dict)
        context = {
            'pedido': obj_pedido,
            'frm_paypal':frm_paypal
        }

        request.session['pedido_id']= obj_pedido.id

        return render (request,'pago.html',context)

@login_required(login_url='/login')
def gracias(request):
    paypal_id = request.GET.get('PayerID',None)
    if paypal_id is not None:
        pedido_id = request.session.get('pedido_id')
        pedido = Pedido.objects.get(pk=pedido_id)
        pedido.estado = '1'
        pedido.save()

        request.session['pedido_id'] = None
        carrito = Cart(request)
        carrito.clear()

    return render(request,'gracias.html')

@login_required(login_url='/login')

alura/templates/includes/catalog/cursos.html
{% load static %}
<div class="row prod-items prod-items-2">
    {% for curso in cursos %}
    <article
      class="cf-sm-6 cf-md-6 cf-lg-6 col-xs-6 col-sm-6 col-md-6 col-lg-6 sectgl-item"
    >
      <div class="sectgl prod-i">
        <div class="prod-i-top">
          <a class="prod-i-img" href="/curso/{{curso.id}}">
            {% if curso.cursoimagen_set.exists %}
            <img src="{{curso.cursoimagen_set.first.imagen.url}}" alt="" />
            {% else %}
            <img src="http://placehold.it/290x258" alt="" />
            {% endif %}
          </a>
          <div class="prod-i-actions">
            <div class="prod-i-actions-in">
              <div class="prod-li-favorites">
                <a
                  href="wishlist.html"
                  class="hover-label add_to_wishlist"
                  ><i class="icon ion-heart"></i
                  ><span>Add to Wishlist</span></a
                >
              </div>
              <p class="prod-quickview">
                <a href="#" class="hover-label quick-view"
                  ><i class="icon ion-plus"></i
                  ><span>Quick View</span></a
                >
              </p>
              <p class="prod-i-cart">
                <a href="/carrito/add/{{curso.id}}" class="hover-label prod-addbtn"
                  ><i class="icon ion-android-cart"></i
                  ><span>Add to Cart</span></a
                >
              </p>
              <p class="prod-li-compare">
                <a
                  href="compare.html"
                  class="hover-label prod-li-compare-btn"
                  ><span>Compare</span
                  ><i class="icon ion-arrow-swap"></i
                ></a>
              </p>
            </div>
          </div>
        </div>
        <div class="prod-i-bot">
          <div class="prod-i-info">
            <p class="prod-i-price">S/.{{curso.precio}}</p>
            <p class="prod-i-categ">
              <a href="catalog-gallery.html">{{curso.categoria.nombre}}</a>
            </p>
          </div>
          <h3 class="prod-i-ttl">
            <a href="/curso/{{curso.id}}">{{curso.curso}}</a>
          </h3>
        </div>
      </div>
    </article>
    {% endfor %}
  </div>
  <ul class="page-numbers">
    <li><span class="page-numbers current">1</span></li>
    <li><a class="page-numbers" href="#">2</a></li>
    <li><a class="page-numbers" href="#">3</a></li>
    <li><a class="page-numbers" href="#">4</a></li>
    <li>
      <a class="next page-numbers" href="#"
        ><i class="fa fa-angle-right"></i
      ></a>
    </li>
  </ul>

alura/templates/includes/catalog/filters.html
{% load static %}
<aside class="blog-sb-widgets section-sb" id="section-sb">
    <div class="theiaStickySidebar">
      <p class="section-filter-toggle filter_hidden">
        <a href="#" id="section-filter-toggle-btn">Filtros</a>
      </p>
      <div class="section-filter">
        <div class="section-filter">
          <div class="blog-sb-widget multishopcategories_widget">
            <h3 class="widgettitle">Categorias</h3>
            <div class="section-sb-current">
              <ul class="section-sb-list">
                <li>
                  <a href="/cursos"
                    ><span class="section-sb-label"
                      >Todas
                      <span class="count">{{cursos.count}} </span></span
                    ></a
                  >
                </li>
                {% for categoria in categorias %}
                <li>
                  <a href="/cursos?cat={{categoria.id}}"
                    ><span class="section-sb-label"
                      >{{categoria.nombre}}
                      <span class="count">{{categoria.curso_set.all.count}} </span></span
                    ></a
                  >
                </li>
                {% endfor %}
              </ul>
            </div>
          </div>
          <div class="blog-sb-widget multishopbrands_widget">
            <h3 class="widgettitle">Areas</h3>
            <ul class="brands-list-sb">
              {% for area in areas %}
              <li>
                <a href="/cursos?are={{area.id}}">{{area.nombre}}<span class="count">{{area.curso_set.all.count}} </span></a>
              </li>
              {% endfor %}
            </ul>
          </div>
        </div>
      </div>
    </div>
</aside>

alura/templates/includes/catalog/top.html
{% load static %}
<div class="section-top">
    <h1 class="maincont-ttl">Cursos Alura</h1>
    <ul class="b-crumbs">
      <li><a href="index.html">Home</a></li>
      <li>Cursos</li>
    </ul>
    <div class="section-top-sort">
      <div class="section-view">
        <p>View</p>
        <div class="dropdown-wrap">
          <p class="dropdown-title section-view-ttl">Gallery</p>
          <ul class="dropdown-list">
            <li>
              <a href="catalog-list.html">List</a>
            </li>
            <li class="active">
              <a href="catalog-gallery.html">Gallery</a>
            </li>
          </ul>
        </div>
      </div>
      <div class="section-sort">
        <p>Sort</p>
        <div class="dropdown-wrap">
          <p class="dropdown-title section-sort-ttl">Newness</p>
          <ul class="dropdown-list">
            <li>
              <a href="#">Popularity</a>
            </li>
            <li>
              <a href="#">Average rating</a>
            </li>
            <li class="active">
              <a href="#">Newness</a>
            </li>
            <li>
              <a href="#">Price: low to high</a>
            </li>
            <li>
              <a href="#">Price: high to low</a>
            </li>
          </ul>
        </div>
      </div>
      <form method="post" class="products-per-page">
        <p>Per Page</p>
        <select>
          <option value="12" selected="selected">12</option>
          <option value="24">24</option>
          <option value="48">48</option>
          <option value="-1">All</option>
        </select>
      </form>
    </div>
  </div>